baseURL = "https://ox-hugo.scripter.co/"

Title = "ox-hugo - Org to Hugo exporter"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

# Remove files from destination not found in static directories
cleandestinationdir = true

# Mon Mar 05 17:17:44 EST 2018 - kmodi
# Do not enable GitInfo. As I am not committing the Markdown files to
# git repo, enabling GitInfo would cause the Lastmod dates for those
# files to be the date when I deleted them from this repo.. sigh.
# enableGitInfo = true

enableEmoji = true

LanguageCode = "en-us" # Used in RSS generation

disableFastRender = true        # Hugo 0.30

disableKinds = ["taxonomy", "taxonomyTerm"]

[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-onyx-theme"
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-debugprint"

[markup]
  [markup.highlight]
    codeFences = true # default = true
    noClasses = false # default = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "1m" # Disable caching getJSON data

[Permalinks]
  # post = "/:year/:month/:title/"
  # Below, we have
  #   foo = "bar"
  # where foo = section name without double quotes for which we want to have
  # the custom permalinks. If foo is 'posts', it will apply to content in
  # content/posts/ dir. The "bar" portion is how you want the links to look.
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  doc = "/doc/:filename/"
  test = "/test/:slug/"

[Params]
  name = "ox-hugo"
  description = "Org mode to Hugo exporter<br />Write your Hugo posts in native Org mode."

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  github_user = "kaushalmodi"
  github_repo = "ox-hugo"
  github_workflow_file = "test.yml"
  github_banner = true

  images = ["/favicon-196x196.png"] # Used in twitter_cards.html partial

  custom_css = [ # Chroma Trac theme
                 # "css/trac_chroma.css" # Needs markup.highlight.noClasses to be false
                 # Chroma GitHub theme
                 "css/github_chroma.css" # Needs markup.highlight.noClasses to be false
                 , "css/style.css"
               ]
  custom_css_absolute = [ # Iosevka fonts
                          "https://cdn.rawgit.com/kaushalmodi/iosevka-mirror/v1.14.1/iosevka.css"
                        ]
  custom_js  = []

  # favicon = "favicon.ico"

  [Params.source]
    url = "https://github.com/kaushalmodi/ox-hugo"
    default_branch = "main"
    org_dir = "doc"
    org_file = "doc/ox-hugo-manual.org"

  [Params.sidebar]
    logo = "favicon.ico"

    github_button  = true
    gha_button  = true
    codecov_button = false
    gratipay = ""

    # Mon Sep 04 23:55:36 EDT 2017 - kmodi
    # Disable this option for now.. but seems to be useful in future
    show_relations = false

  [Params.footer]
    copyright = ""
    show_powered_by = true
