trigger:
  branches:
    include:
    - master
    - ci
    - azure-pipelines
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
    - doc

pr:
- master

strategy:
  matrix:
    # Sometimes fails.
    windows-2019:
      IMAGE_NAME: 'windows-2019'

    # Always fails: ValueError: Could not determine the version of Emacs at emacs
    # macos-10.15-emacs-25.3:
    #   IMAGE_NAME: 'macos-10.15'
    #   EVM_EMACS: emacs-25.3
    # macos-10.15-emacs-26.3:
    #   IMAGE_NAME: 'macos-10.15'
    #   EVM_EMACS: emacs-26.3
    macos-10.15-emacs-27.1:
      IMAGE_NAME: 'macos-10.15'
      EVM_EMACS: emacs-27.1

    ubuntu-18.04-emacs-25.3:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-25.3
    ubuntu-18.04-emacs-26.3:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-26.3
    ubuntu-18.04-emacs-27.1:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-27.1

pool:
  vmImage: $(IMAGE_NAME)

resources:
  repositories:
  - repository: emacs-module-rs
    type: github
    name: ubolonton/emacs-module-rs
    ref: azure-pipelines
    endpoint: emacs-tree-sitter

steps:
- checkout: self
  submodules: true
- template: .azure-pipelines/steps/setup-rust.yml@emacs-module-rs
- template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
- template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
- template: steps/-build.yml
- template: steps/setup-tree-sitter-cli.yml
- template: steps/-test.yml
