steps:
- powershell: |
    .\bin\ensure-lang.ps1 rust
    .\bin\ensure-lang.ps1 javascript
    .\bin\ensure-lang.ps1 bash
    .\bin\test.ps1
  displayName: Run tests (Windows)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- bash: |
    set -e
    make test
  displayName: Run tests
  condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'))
