name: Shell

on:
  workflow_dispatch:
    inputs:
      revision:
        required: true
        default: 'master'
      platform:
        required: true
        default: macos-latest
        description: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

jobs:
  build:
    runs-on: ${{ github.event.inputs.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.revision }}
    - uses: mxschmitt/action-tmate@v3
      name: Setup tmate session
